# Generated by Django 3.2.8 on 2022-09-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
